### ISSUE TITLE
`{{#link-to}}` blocks?

### ISSUE THREAD

**Issue by thewatts** [code0100fun/hbars#3]
Hey @code0100fun! `hbars` is super legit! Great work!

I'm curious - what's the proper syntax for doing `{{#link-to}}` blocks?

example, in `HTMLBars`:

``` handlebars
{{#link-to "photo.edit" photo}}
  Edit Photo
{{/link-to}}
```

Thanks!

**Comment by code0100fun** [comment]
Sorry for the delay. Been working heavily on some other Ember stuff lately.

The intended syntax was something [like if/else](http://www.hbars.io/if-else-unless). Just realized the parser does not accept quoted parameters for expressions with blocks this won't work right now:

``` haml
- foo "bar" baz
  Qux
```

I will work on fixing this soon. So the syntax for `link-to` will be:

``` haml
- link-to "photo.edit" photo
  Edit Photo
```

**Comment by code0100fun** [comment]
Actually, I realized this is actually working. You can check it at [hbars.io](http://hbars.io). Just paste in the above `link-to` into the hbars section.
